M48
; DRILL file {KiCad 9.0.7} date 2026-07-10T16:16:15+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-10T16:16:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X76.68Y-100.59
X76.68Y-106.37
T2
X94.2Y-61.68
X107.6Y-61.68
X112.28Y-61.68
M30
